# Generated by Django 5.0.1 on 2024-01-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_candidateapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('No Experience', 'No Experience'), ('1 Years', 'One Year'), ('2 Years', 'Two Year'), ('3 Years above', 'Three Year Plus')], default='No Experience', max_length=20),
        ),
    ]
